name: Update CM components
on:
  push:
    branches:
       - master
    #  - github-actions-for-production-approval
    # File paths to consider in the event. Optional; defaults to all.
    # paths:
    #  - "components.yaml"

jobs:
  my-job:
    name: Update CM components
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Create File
        run: |
          #pip install yq
          #export COMPONENT_ID=$(cat components.yaml | yq .components | yq -r ".[0]".componentId)
          export COMPONENT_ID=testID
          export COMPONENTS_YAML_CONTENT=$(cat components.yaml | tr -d '\n')
          echo ---
          echo "$COMPONENTS_YAML_CONTENT"
          echo ----
          echo "::set-env name=CMP_ID::${COMPONENT_ID}"
          echo "::set-env name=CMPS_YAML_CONTENT::${COMPONENTS_YAML_CONTENT}"
      - name: Print dir info 1
        run: |
          pwd
          ls -la
          ls -la /home
      - name: Update components yaml file in qlik-trial/cm
        uses: mtk7801/github_action_run_command_and_create_pr@master
        with:
          gh_token: ${{ secrets.SVC_PIPELINE_TOKEN }}
          group: qlik-trial
          repository: elastic-pipeline
          branch: update_components_for_${{ env.CMP_ID }}
          command: "pwd; ls -la /github; ls -la /github/home; ls -la /github/workspace; echo ${{ env.CMP_ID }}; echo HEJ; echo ${{ env.CMPS_YAML_CONTENT }}"
          commit_msg: "Updated components for ${{ env.CMP_ID }}"
          draft: false
          user: svc-pipeline
          email: svc_pipeline@qlik.com
          label: automerge
      - name: Print dir info 2
        run: |
          pwd
          ls -la
